language: go

go:
  - "1.10.x"  

before_install:
  - go get -v github.com/golang/lint/golint

install:
  - # skip

script:
 - pwd && ls ./ && ls ../
 - cd ../ && mv bk-cmdb ../../configcenter
 - cd ../../configcenter/src
 - pwd && ls ./
 - make server
