language: go

go:
  - "1.8.x"
  - "1.10.x"  

# safelist
branches:
  only:
  - master
  
env:
  global:
    - REPO_NAME=bk-cmdb
    - BUILD_DIR=configcenter
  
before_install:
  - go get -v github.com/golang/lint/golint

install: true

script:
 - pwd && ls ./ && ls ../
 - cd ../ && mv $REPO_NAME ../../$BUILD_DIR
 - cd ../../$BUILD_DIR
 - ./pre-commit.sh
 - cd src
 - make

notifications:
  email:
    recipients:
      - gmaclinuxer@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
