language: go

go:
  - "1.8.x"
  - "1.10.x"  

before_install:
  - go get -v github.com/golang/lint/golint

install: true

script:
 - pwd && ls ./ && ls ../
 - cd ../ && mv bk-cmdb ../../configcenter
 - cd ../../configcenter/src
 - pwd && ls ./
 - make

notifications:
  email:
    recipients:
      - 564034165@qq.com
      - gmaclinuxer@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
